/**
 * Image and table generation for voice computer control.
 *
 * Images come from the Codex CLI's native `imagegen` tool rather than a direct
 * API call, so no API key has to be stored or managed by this app. Two facts
 * about that tool were established by reading past session rollouts and by
 * running the CLI:
 *
 *  - `imagegen` returns a base64 PNG inline (function_call_output carries
 *    `data:image/png;base64,…` with C2PA provenance), so it is a first-party
 *    tool, not a wrapper around a user-supplied key.
 *  - it is only attached on the larger models. Every rollout that used it ran
 *    `gpt-5.6-sol`; the default `gpt-5.3-codex-spark` silently falls back to
 *    drawing with PIL, which produces a shape rather than an illustration.
 *    {@link IMAGE_MODEL} therefore pins the model instead of inheriting it.
 *
 * Tables are not generated by a model at all. Turning rows the user dictated
 * into Markdown is deterministic, and a model would only add latency and the
 * chance of inventing a row.
 */
import { execFile as execFileCallback } from 'child_process'
import fs from 'fs'
import os from 'os'
import path from 'path'
import { promisify } from 'util'
import { logInfo, logWarn } from './logger.ts'

const execFile = promisify(execFileCallback)

/** Pinned because `imagegen` is not attached to the default model. */
export const IMAGE_MODEL = 'gpt-5.6-sol'
const IMAGE_TIMEOUT_MS = 300_000
const MAX_PROMPT_LENGTH = 800
const OUTPUT_NAME = 'generated.png'
const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47])

export interface GeneratedImage {
  path: string
  bytes: number
  model: string
}

export class ImageGenerationError extends Error {
  // Written out rather than declared as a parameter property: the verification
  // scripts run these modules through Node's type-stripping loader, which does
  // not support that syntax.
  readonly detail?: string

  constructor(message: string, detail?: string) {
    super(message)
    this.name = 'ImageGenerationError'
    this.detail = detail
  }
}

function resolveCodexBinary(): string | null {
  const candidates = [
    process.env.NOVA_CODEX_BIN,
    '/opt/homebrew/bin/codex',
    '/usr/local/bin/codex',
    path.join(os.homedir(), '.local', 'bin', 'codex'),
  ].filter((candidate): candidate is string => Boolean(candidate))
  return candidates.find((candidate) => fs.existsSync(candidate)) ?? null
}

/**
 * True when the file is really a PNG.
 *
 * The CLI reports success in prose, and a model can claim to have written a
 * file it never wrote. Only the bytes on disk settle it.
 */
function isPng(filePath: string): boolean {
  try {
    const handle = fs.openSync(filePath, 'r')
    try {
      const header = Buffer.alloc(4)
      fs.readSync(handle, header, 0, 4, 0)
      return header.equals(PNG_MAGIC)
    } finally {
      fs.closeSync(handle)
    }
  } catch {
    return false
  }
}

/**
 * Generates one image from a spoken description.
 *
 * The description is passed as a single `execFile` argument, never interpolated
 * into a shell string, so a request containing quotes or semicolons stays a
 * description. The Codex sandbox is additionally confined to the scratch
 * directory created here.
 */
export async function generateImage(
  description: string,
  signal?: AbortSignal,
): Promise<GeneratedImage> {
  const prompt = description.replace(/\s+/g, ' ').trim().slice(0, MAX_PROMPT_LENGTH)
  if (!prompt) throw new ImageGenerationError('무엇을 그릴지 알려주세요.')

  const binary = resolveCodexBinary()
  if (!binary) {
    throw new ImageGenerationError(
      'Codex CLI를 찾지 못했습니다. 이미지 생성에는 codex가 필요합니다.',
    )
  }

  const workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nova-image-'))
  const outputPath = path.join(workDir, OUTPUT_NAME)
  try {
    // Codex refuses to run outside a repository unless told to skip the check,
    // and it reads stdin when none is supplied, which would hang a background
    // call. Both are handled explicitly rather than left to default behaviour.
    await execFile(binary, [
      'exec',
      '--model', IMAGE_MODEL,
      '--sandbox', 'workspace-write',
      '--skip-git-repo-check',
      '--cd', workDir,
      [
        'Use the imagegen tool to create this image:',
        prompt,
        `Then save the generated image as ${OUTPUT_NAME} in the working directory.`,
        'Do not draw it with code — use the imagegen tool.',
      ].join(' '),
    ], {
      timeout: IMAGE_TIMEOUT_MS,
      cwd: workDir,
      signal,
      maxBuffer: 8 * 1024 * 1024,
      // stdin is closed so the CLI does not block waiting for input.
      stdio: ['ignore', 'pipe', 'pipe'],
    } as Parameters<typeof execFile>[2])

    if (!fs.existsSync(outputPath)) {
      throw new ImageGenerationError('이미지가 생성되지 않았습니다.', `${outputPath} not found`)
    }
    if (!isPng(outputPath)) {
      throw new ImageGenerationError('생성된 파일이 이미지가 아닙니다.', 'PNG magic bytes missing')
    }

    const bytes = fs.statSync(outputPath).size
    logInfo('[ImageGen] Generated', { bytes, model: IMAGE_MODEL })
    return { path: outputPath, bytes, model: IMAGE_MODEL }
  } catch (error) {
    // The scratch directory is only kept when an image survived in it.
    try {
      fs.rmSync(workDir, { recursive: true, force: true })
    } catch {
      // Nothing further to do about a scratch directory that will not delete.
    }
    if (error instanceof ImageGenerationError) throw error
    const detail = error instanceof Error ? error.message : String(error)
    logWarn('[ImageGen] Failed', { detail })
    if (/usage limit/i.test(detail)) {
      throw new ImageGenerationError('Codex 사용량이 소진되어 이미지를 만들지 못했습니다.', detail)
    }
    throw new ImageGenerationError('이미지 생성에 실패했습니다.', detail)
  }
}

/** Removes a scratch directory returned by {@link generateImage}. */
export function discardGeneratedImage(imagePath: string): void {
  try {
    fs.rmSync(path.dirname(imagePath), { recursive: true, force: true })
  } catch {
    // A leftover temp directory is not worth surfacing to the user.
  }
}

/**
 * Renders dictated rows as a Markdown table.
 *
 * Deterministic on purpose: the user said the contents, so a model could only
 * reword or invent them. Cells are escaped so a value containing a pipe cannot
 * silently split into two columns.
 */
export function generateTable(rows: string[][]): string {
  if (!rows.length || !rows[0].length) return ''
  const width = Math.max(...rows.map((row) => row.length))
  const escape = (cell: string) => cell.replace(/\|/g, '\\|').replace(/\n/g, ' ').trim()
  const pad = (row: string[]) => Array.from({ length: width }, (_, i) => escape(row[i] ?? ''))

  const [header, ...body] = rows
  return [
    `| ${pad(header).join(' | ')} |`,
    `| ${Array.from({ length: width }, () => '---').join(' | ')} |`,
    ...body.map((row) => `| ${pad(row).join(' | ')} |`),
  ].join('\n')
}
